# The language is a lie but eh, maybe in the future we'll use some C
# code.
language: c
addons:
  apt:
    packages:
      - automake
      - autotools-dev
script:
  # For now, just a syntax check.
  - bash -n container-storage-setup.sh

notifications:
  webhooks: http://escher.verbum.org:54856/travis
  email: false

branches:
  only:
    - auto

